# Generated by Django 5.2.6 on 2025-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=500)),
                ('projectDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
