# Generated by Django 5.2.6 on 2025-10-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
